Test julia ci (#17)
* Implement CI for Julia code

---------

Co-authored-by: Adomas Baliuka <A.Baliuka@physik.uni-muenchen.de>

diff --git a/.github/workflows/ci-cmake_tests.yml b/.github/workflows/ci-cmake_tests.yml
--- a/.github/workflows/ci-cmake_tests.yml
+++ b/.github/workflows/ci-cmake_tests.yml
@@ -22,8 +22,33 @@ defaults:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
+  test_julia_scripts:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout this repository
+        uses: actions/checkout@v3
+
+      - name: Install Julia
+        uses: julia-actions/setup-julia@v1
+        with:
+            version: "1" # This will automatically pick the latest Julia version
+
+      - name: instantiate Julia dependencies
+        working-directory: ${{runner.workspace}}/LDPC4QKD/codes
+        run: julia --project -e 'import Pkg; Pkg.instantiate()'
+
+      - name: test julia scripts to make sure they are up to date. This is not part of code coverage!
+        working-directory: ${{runner.workspace}}/LDPC4QKD/codes
+        run: |
+            julia --project --  "./ldpc_codegen.jl" --input_code_path '../tests/test_reading_bincscjson_format_block_6144_proto_2x6_313422410401.bincsc.json' --output_path "./tmp.hpp"
+            expected="37eed538eb42205587dc1b6a4a805a16a9797c4cbcb478cc019f338b9d090c80  ./tmp.hpp"
+            actualoutput="$(sha256sum ./tmp.hpp)"
+            if [ "$actualoutput" != "$expected" ]; then
+                echo "Error on testing sha256 of output: EXPECTED=$expected ACTUAL=$actualoutput"
+                exit 2
+            fi
+
+  build__and_test_cpp_programs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -88,5 +113,3 @@ jobs:
         if: failure()
         working-directory: ${{runner.workspace}}
         run: tree
-        
-    
