Maybe fix CI now

diff --git a/.github/workflows/ci-cmake_tests.yml b/.github/workflows/ci-cmake_tests.yml
--- a/.github/workflows/ci-cmake_tests.yml
+++ b/.github/workflows/ci-cmake_tests.yml
@@ -24,23 +24,26 @@ defaults:
 jobs:
   test_julia_scripts:
     runs-on: ubuntu-latest
-    env:
-      JULIA_NUM_THREADS: 2
     steps:
-      - run: git config --global core.autocrlf false
-      - uses: actions/checkout@v2
-      - uses: julia-actions/setup-julia@v1
-      - uses: julia-actions/julia-buildpkg@v1
+      - name: Checkout this repository
+            uses: actions/checkout@v3
+
+      - name: Install Julia
+        uses: julia-actions/setup-julia@v1
+        with:
+            version: "1" # This will automatically pick the latest Julia version
+
       - name: test julia scripts to make sure they are up to date. This is not part of code coverage!
         working-directory: ${{runner.workspace}}/codes
         run: |
-          julia --project --  "./ldpc_codegen.jl" --input_code_path '../tests/test_reading_bincscjson_format_block_6144_proto_2x6_313422410401.bincsc.json' --output_path "./tmp.hpp"
-          output="$(sha256sum ./tmp.hpp)"
-          expected="37eed538eb42205587dc1b6a4a805a16a9797c4cbcb478cc019f338b9d090c80  ./tmp.hpp"
-          if [ "$expected" != "$actual" ]; then
-            echo "$msg EXPECTED=$expected ACTUAL=$actual"
-            exit 2
-          fi
+            julia --project --  "./ldpc_codegen.jl" --input_code_path '../tests/test_reading_bincscjson_format_block_6144_proto_2x6_313422410401.bincsc.json' --output_path "./tmp.hpp"
+            output="$(sha256sum ./tmp.hpp)"
+            expected="37eed538eb42205587dc1b6a4a805a16a9797c4cbcb478cc019f338b9d090c80  ./tmp.hpp"
+            if [ "$expected" != "$actual" ]; then
+                echo "Error on testing sha256 of output: EXPECTED=$expected ACTUAL=$actual"
+                exit 2
+            fi
+
   build__and_test_cpp_programs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
